version: '3.4'

services:
  decentreadsapi:
    image: ${DOCKER_REGISTRY-}decentreadsapi
    build:
      context: .
      dockerfile: DecentReadsApi/Dockerfile
    ports:
      - "8080:80"  





  


